services:
  - type: web
    name: events-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker backend:app --bind "0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FRONTEND_URL
        value: https://your-frontend-app.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: your-db-name
          property: connectionString
    autoDeploy: false
  - type: web
    name: events-dashboard-frontend
    env: node
    plan: free
    rootDir: frontend
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npx serve -s build
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: REACT_APP_API_URL
        value: https://events-dashboard-be.onrender.com
      - key: PUBLIC_URL
        value: "."
    autoDeploy: false 