services:
  - type: web
    name: events-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: sh -c 'echo "INFO: Attempting to bind to PORT: $PORT" && gunicorn -w 4 -k uvicorn.workers.UvicornWorker backend:app --bind "0.0.0.0:$PORT"'
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FRONTEND_URL
        value: https://your-frontend-app.vercel.app
    autoDeploy: false 